#ifndef IRC_ERROR_HH
# define IRC_ERROR_HH

/// \enum Error
enum IrcError
{
	UNKNOWN_ERROR,
	SOCKET_REMOTECLOSE_ERROR,
	SOCKET_HOSTNOTFOUND_ERROR,
	SOCKET_CONNECTIONREFUSED_ERROR,
	SYNTAX_ERROR,
};

#endif /* !IRC_ERROR_HH */
